---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java 11 vars
      set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ java_oracle_jdk_package }}"
        mode: 0644
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        mode: 0644
        path: "{{ java_home }}"
      tags: java
    - name: Extract java in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
      tags:
        - java
    - name: Export environment variables
      become: true
      template:
        src: jdk.sh.j2
        mode: 0644
        dest: /etc/profile.d/jdk.sh
      tags: java

- name: Install elasticsearch
  hosts: elasticsearch
  handlers:
    - name: Restart elascticsearch
      become: true
      systemd:
        name: elasticsearch
        state: restarted
        enabled: true
  tasks:
    - name: Upload tar.gz Elasticsearch from remote URL
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-x86_64.rpm"
        dest: "/tmp/elasticsearch-{{ elastic_version }}-x86_64.rpm"
      register: get_elastic
      until: get_elastic is succeeded
      tags: elastic
    - name: Install rpm package elasticsearch
      become: true  
      yum:
          name: "/tmp/elasticsearch-{{ elastic_version }}-x86_64.rpm"
          state: present
      tags: elasticsearch
    - name: Configure elasticsearch
      become: true
      template:
        src: elasticsearch.yml.j2
        mode: 0644
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: Restart elascticsearch
      tags: elasticsearch

- name: Install Kibana
  hosts: kibana
  handlers:
    - name: restart Kibana
      become: true
      systemd:
        name: kibana
        state: restarted
        enabled: true
  tasks:
    - name: "Download Kibana rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
        dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
      register: download_kibana
      until: download_kibana is succeeded
      tags: kibana
    - name: Install rpm package kibana
      become: true  
      yum:
          name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
          state: present
      notify: restart Kibana
      tags: kibana
    - name: Configure Kibana
      become: true
      template:
        src: kibana.yml.j2
        mode: 0644
        dest: /etc/kibana/kibana.yml
      notify: restart Kibana
      tags: kibana
      
- name: Install filebeat
  hosts: app
  handlers:
    - name: restart filebeat
      become: true
      systemd:
        name: filebeat
        state: restarted
        enabled: true
  tasks:
    - name: "Download filebeat rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
      register: download_filebeat
      until: download_filebeat is succeeded
      tags: filebeat
    - name: Install rpm package filebeat
      become: true  
      yum:
          name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
          state: present
      notify: restart filebeat
      tags: filebeat
    - name: Configure filebeat
      become: true
      template:
        src: filebeat.yml.j2
        mode: 0644
        dest: /etc/filebeat/filebeat.yml
      notify: restart filebeat
      tags: filebeat
    - name: Set filebeat systemwork
      become: true
      command:
        cmd: filebeat modules enable system
        chdir: /usr/share/filebeat/bin
      register: filebeat_modules
      changed_when: filebeat_modules.stdout != 'Module system is already enabled'
    - name: Load Kibana dashboard
      become: true
      command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      until: filebeat_setup is succeeded
      changed_when: false


