---
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 62.84.117.75
      ansible_user: falconow
kibana:
  hosts:
    k-instance:
      ansible_host: 178.154.241.46
app:
  hosts:
    application-instance:
      ansible_host: 62.84.115.21